checks:
  - check: message
    regex: '^(?:Revert "[A-Z][A-Z0-9]+-\d+: .+"|(?:(feat|fix|perf|refactor|docs|style|test|build|ci|chore|revert|security|task): )?[A-Z][A-Z0-9]+-\d+: .+(?:\n\n.*(?:\n.*)*)?$)|Merge.+$'
    error: |
      The commit message should be structured as follows:

      [optional <type>: ]<JIRA_ISSUE_KEY>: <description>
      OR
      Revert "<JIRA_ISSUE_KEY>: <description>"

      [optional body]
      [optional footer(s)]

      More details please refer to https://www.conventionalcommits.org
    suggest: please check your commit message whether matches above regex

  - check: branch
    regex: '^(?:revert-\d+-)?(?:bugfix|feature|release|hotfix|task|chore)\/[A-Z0-9]+-\d+-.*|master|main|HEAD|PR-\d+|dependabot\/.*|claude\/.*'
    error: "Branches must begin with these types: bugfix/ feature/ release/ hotfix/ task/ chore/ followed by the JIRA_ISSUE_KEY and a hyphenated description or revert-<PR_NUMBER>-<BRANCH_NAME>"
    suggest: run command `git checkout -b type/<JIRA_ISSUE_KEY>-<hyphenated-description>`

  - check: author_name
    regex: ^[A-Za-zÀ-ÖØ-öø-ÿ\u0100-\u017F\u0180-\u024F ,.\'-]+$|.*(\[bot])
    error: The committer name seems invalid
    suggest: run command `git config user.name "Your Name"`

  - check: author_email
    regex: ^(?:.+@saaslabs.co)|(?:.+saas-labs-sherlock\[bot\].+)|(?:.+dependabot.+)$
    error: The committer email seems invalid
    suggest: run command `git config user.email officialemail@saaslabs.co`
