name: Validate Git Hygiene
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  git-hygiene:
    uses: saaslabsco/ci-workflows/.github/workflows/git-hygiene-reusable.yml@master
    name: Validate Git Hygiene